-- Oyeola lead intake schema.
-- Run this in the Supabase project used by oyeola-web before enabling the production form endpoint.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('contact','website-check','operations-check','planner-download','start-here')),
  name text,
  email text not null,
  service_type text,
  business_url text,
  problem text,
  desired_result text,
  timeline text,
  source_page text,
  score numeric,
  result_label text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

revoke all on table public.leads from anon, authenticated;
grant insert on table public.leads to anon, authenticated;
grant usage, select on sequence public.leads_id_seq to anon, authenticated;

create policy "allow public lead submissions"
on public.leads
for insert
to anon, authenticated
with check (
  email is not null
  and length(email) between 3 and 320
  and type in ('contact','website-check','operations-check','planner-download','start-here')
);

-- There is intentionally no SELECT/UPDATE/DELETE policy for public roles.
-- Leads remain unreadable through the public Data API.
