-- Oyeola lead-capture schema for Supabase project pnuyufllwzultgrgpotz
-- Run this once in the Supabase SQL editor for that project.

create table if not exists public.oyeola_leads (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  source text not null default 'website',
  interest text,
  website_url text,
  message text,
  page_url text,
  created_at timestamptz not null default now()
);

create index if not exists oyeola_leads_created_at_idx on public.oyeola_leads (created_at desc);
create index if not exists oyeola_leads_email_idx on public.oyeola_leads (lower(email));
create index if not exists oyeola_leads_source_idx on public.oyeola_leads (source);

alter table public.oyeola_leads enable row level security;

-- No browser-side read/update/delete policy is created.
-- The production /api/lead endpoint writes server-side using a Vercel secret.
-- This intentionally keeps the lead database unreadable from the public website.

comment on table public.oyeola_leads is 'Website, diagnostic and planner-resource leads submitted through Oyeola Online.';
